#!/bin/bash
. .quick-navigation/shells

if [ $# -ne 1 ]; then
	echo "Usage: $0 <new-map's-name>"
	echo "e.g.) $0 my-room"
	exit 1
fi


_TEMPLATE_DIR_=${_DATA_DIR_}/.template

_NEW_MAP_DIR_=${_DATA_DIR_}/${1}


if [ -d ${_NEW_MAP_DIR_} ]; then
	echo "Error: $1 already exists"
	exit 1
fi


mkdir ${_NEW_MAP_DIR_}
if [ $? -eq 0 ]; then
	echo "make new map data directory ${_NEW_MAP_DIR_}"
else
	echo "fail to make directory ${_NEW_MAP_DIR_}"
	exit 1
fi


# opsm-position-tracker
if [ -f ${_TEMPLATE_DIR_}/${_P_TRACKER_CONF_} ]; then
	cp ${_TEMPLATE_DIR_}/${_P_TRACKER_CONF_} ${_NEW_MAP_DIR_}/
	echo "${_P_TRACKER_CONF_} ... ok"
else 
	echo "Error: ${_TEMPLATE_DIR_}/${_P_TRACKER_CONF_} is not exist"
fi

# opsm-particle-evaluator
if [ -f ${_TEMPLATE_DIR_}/${_P_EVALUATOR_CONF_} ]; then
	cp ${_TEMPLATE_DIR_}/${_P_EVALUATOR_CONF_} ${_NEW_MAP_DIR_}/
	echo "${_P_TRACKER_CONF_} ... ok"
else 
	echo "Error: ${_TEMPLATE_DIR_}/${_P_EVALUATOR_CONF_} is not exist"
fi

# particle-localizer
if [ -f ${_TEMPLATE_DIR_}/${_LOCLIZER_CONF_} ]; then
	cp ${_TEMPLATE_DIR_}/${_LOCLIZER_CONF_} ${_NEW_MAP_DIR_}/
	echo "${_LOCLIZER_CONF_} ... ok"
else 
	echo "Error: ${_TEMPLATE_DIR_}/${_LOCLIZER_CONF_} is not exist"
fi

# path-planner
if [ -f ${_TEMPLATE_DIR_}/${_PATH_PLAN_CONF_} ]; then
	cp ${_TEMPLATE_DIR_}/${_PATH_PLAN_CONF_} ${_NEW_MAP_DIR_}/
	echo "${_PATH_PLAN_CONF_} ... ok"
else 
	echo "Error: ${_TEMPLATE_DIR_}/${_PATH_PLAN_CONF_} is not exist"
fi
if [ -f ${_TEMPLATE_DIR_}/${_PATH_PLAN_OPT_} ]; then
	cp ${_TEMPLATE_DIR_}/${_PATH_PLAN_OPT_} ${_NEW_MAP_DIR_}/${_PATH_PLAN_OPT_}
	echo "${_PATH_PLAN_OPT_} ... ok"
else 
	echo "Error: ${_TEMPLATE_DIR_}/${_PATH_PLAN_OPT_} is not exist"
fi


# route-editor
if [ -f ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_CONF_} ]; then
	cp ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_CONF_} ${_NEW_MAP_DIR_}/
	echo "${_ROUTE_EDITOR_CONF_} ... ok"
else 
	echo "Error: ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_CONF_} is not exist"
fi
if [ -f ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_OPT_} ]; then
	cp ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_OPT_} ${_NEW_MAP_DIR_}/${_ROUTE_EDITOR_OPT_}
	echo "${_ROUTE_EDITOR_OPT_} ... ok"
else 
	echo "Error: ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_OPT_} is not exist"
fi


# visualizer
if [ -f ${_TEMPLATE_DIR_}/${_VISUALIZER_CONF_} ]; then
	cp ${_TEMPLATE_DIR_}/${_VISUALIZER_CONF_} ${_NEW_MAP_DIR_}/
	echo "${_VISUALIZER_CONF_} ... ok"
else 
	echo "Error: ${_TEMPLATE_DIR_}/${_VISUALIZER_CONF_} is not exist"
fi


# ls-coordinate-converter
if [ -f ${_TEMPLATE_DIR_}/${_LS_CCONVERTER_CONF_} ]; then
	cp ${_TEMPLATE_DIR_}/${_LS_CCONVERTER_CONF_} ${_NEW_MAP_DIR_}/
	echo "${_LS_CCONVERTER_CONF_} ... ok"
else 
	echo "Error: ${_TEMPLATE_DIR_}/${_LS_CCONVERTER_CONF_} is not exist"
fi
if [ -f ${_TEMPLATE_DIR_}/${_LS_CCONVERTER_OPT_} ]; then
	cp ${_TEMPLATE_DIR_}/${_LS_CCONVERTER_OPT_} ${_NEW_MAP_DIR_}/${_LS_CCONVERTER_OPT_}
	echo "${_LS_CCONVERTER_OPT_} ... ok"
else 
	echo "Error: ${_TEMPLATE_DIR_}/${_LS_CCONVERTER_OPT_} is not exist"
fi


./qn-open ${_NEW_MAP_DIR_}

