#!/bin/bash
. .quick-navigation/shells
. ${_META_DATA_}

_MAP_DIR_=${_CURRENT_WORKING_}

# opsm-position-tracker
if [ -f ${_P_TRACKER_DIR_}/${_P_TRACKER_CONF_} ]; then
	cp ${_P_TRACKER_DIR_}/${_P_TRACKER_CONF_} ${_MAP_DIR_}/
	echo "${_MAP_DIR_}/${_P_TRACKER_CONF_} ... ok"
else 
	echo "Error: ${_P_TRACKER_DIR_}/${_P_TRACKER_CONF_} is not exist"
fi

# opsm-particle-evaluator
if [ -f ${_P_EVALUATOR_DIR_}/${_P_EVALUATOR_CONF_} ]; then
	cp ${_P_EVALUATOR_DIR_}/${_P_EVALUATOR_CONF_} ${_MAP_DIR_}/
	echo "${_MAP_DIR_}/${_P_TRACKER_CONF_} ... ok"
else 
	echo "Error: ${_P_EVALUATOR_DIR_}/${_P_EVALUATOR_CONF_} is not exist"
fi

# particle-localizer
if [ -f ${_LOCLIZER_DIR_}/${_LOCLIZER_CONF_} ]; then
	cp ${_LOCLIZER_DIR_}/${_LOCLIZER_CONF_} ${_MAP_DIR_}/
	echo "${_MAP_DIR_}/${_LOCLIZER_CONF_} ... ok"
else 
	echo "Error: ${_LOCLIZER_DIR_}/${_LOCLIZER_CONF_} is not exist"
fi

# path-planner
if [ -f ${_PATH_PLAN_DIR_}/${_PATH_PLAN_CONF_} ]; then
	cp ${_PATH_PLAN_DIR_}/${_PATH_PLAN_CONF_} ${_MAP_DIR_}/
	echo "${_MAP_DIR_}/${_PATH_PLAN_CONF_} ... ok"
else 
	echo "Error: ${_PATH_PLAN_DIR_}/${_PATH_PLAN_CONF_} is not exist"
fi
if [ -f ${_PATH_PLAN_DIR_}/${_LAUNCHER_OPT_} ]; then
	cp ${_PATH_PLAN_DIR_}/${_LAUNCHER_OPT_} ${_MAP_DIR_}/${_PATH_PLAN_OPT_}
	echo "${_MAP_DIR_}/${_PATH_PLAN_OPT_} ... ok"
else 
	echo "Error: ${_PATH_PLAN_DIR_}/${_LAUNCHER_OPT_} is not exist"
fi


# route-editor
if [ -f ${_ROUTE_EDITOR_DIR_}/${_ROUTE_EDITOR_CONF_} ]; then
	cp ${_ROUTE_EDITOR_DIR_}/${_ROUTE_EDITOR_CONF_} ${_MAP_DIR_}/
	echo "${_MAP_DIR_}/${_ROUTE_EDITOR_CONF_} ... ok"
else 
	echo "Error: ${_ROUTE_EDITOR_DIR_}/${_ROUTE_EDITOR_CONF_} is not exist"
fi
if [ -f ${_PATH_PLAN_DIR_}/${_LAUNCHER_OPT_} ]; then
	cp ${_PATH_PLAN_DIR_}/${_LAUNCHER_OPT_} ${_MAP_DIR_}/${_PATH_PLAN_OPT_}
	echo "${_MAP_DIR_}/${_PATH_PLAN_OPT_} ... ok"
else 
	echo "Error: ${_PATH_PLAN_DIR_}/${_LAUNCHER_OPT_} is not exist"
fi


# visualizer
if [ -f ${_VISUALIZER_DIR_}/${_VISUALIZER_CONF_} ]; then
	cp ${_VISUALIZER_DIR_}/${_VISUALIZER_CONF_} ${_MAP_DIR_}/
	echo "${_MAP_DIR_}/${_VISUALIZER_CONF_} ... ok"
else 
	echo "Error: ${_VISUALIZER_DIR_}/${_VISUALIZER_CONF_} is not exist"
fi


# ls-coordinate-converter
if [ -f ${_LS_CCONVERTER_DIR_}/${_LS_CCONVERTER_CONF_} ]; then
	cp ${_LS_CCONVERTER_DIR_}/${_LS_CCONVERTER_CONF_} ${_MAP_DIR_}/
	echo "${_MAP_DIR_}/${_LS_CCONVERTER_CONF_} ... ok"
else 
	echo "Error: ${_LS_CCONVERTER_DIR_}/${_LS_CCONVERTER_CONF_} is not exist"
fi
if [ -f ${_LS_CCONVERTER_DIR_}/${_LAUNCHER_OPT_} ]; then
	cp ${_LS_CCONVERTER_DIR_}/${_LAUNCHER_OPT_} ${_MAP_DIR_}/${_LS_CCONVERTER_OPT_}
	echo "${_MAP_DIR_}/${_LS_CCONVERTER_OPT_} ... ok"
else 
	echo "Error: ${_LS_CCONVERTER_DIR_}/${_LAUNCHER_OPT_} is not exist"
fi


# opsm-map
if [ -d ${_WORKING_}/${_OPSM_MAP_} ]; then
	cp -r ${_WORKING_}/${_OPSM_MAP_} ${_MAP_DIR_}/${_OPSM_MAP_}
	echo "${_OPSM_MAP_} ... ok"
else
	echo "Warnning: ${_OPSM_MAP_} is not exist"
fi

# route
if [ -f ${_WORKING_}/${_ROUTE_} ]; then
	cp ${_WORKING_}/${_ROUTE_} ${_MAP_DIR_}/${_ROUTE_}
	echo "${_ROUTE_} ... ok"
else
	echo "Warnning: ${_ROUTE_} is not exist"
fi

echo "save ${_MAP_DIR_}"

